# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4fed6b6364e13868e8aa602fd8892427419cbb8fc1efacdecf6f80f45bdfb3c24b741cd3420bbd09546872a5ca2a9a0bd6ad0c6ccced6acc21051f813f876a4c

test:
  secret_key_base: 9987b67835f6f2f3a81f8ba5e3d0b0f26676f04e7b0c42a49e372a35e172737e669fba14cce2d1af1162e7cc9f65e293df431760e755c4def79e40c28018d025

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
